<template>
  <div id="home_wrap">
    <ul class="article_area">
      <li class="swing-top-fwd">1</li>
      <li class="swing-top-fwd">2</li>
      <li class="swing-top-fwd">3</li>
      <li class="swing-top-fwd">4</li>
    </ul>
  </div>
</template>

<script>
export default {
  name: "Home"
}
</script>

<style scoped lang="scss">
/* ----------------------------------------------
 * Generated by Animista on 2020-10-14 20:44:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-top-fwd
 * ----------------------------------------
 */

#home_wrap {
  width: 1000px;

  .article_area {
    display: flex;
    flex-direction: row;
    list-style: none;
    text-align: center;
    .swing-top-fwd {
      flex: 1;
      padding: 2rem;
    }
  }
}

/*.swing-top-fwd {
  animation: swing-top-fwd 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

@keyframes swing-top-fwd {
  0% {
    transform: rotateX(0);
    transform-origin: top;
  }
  100% {
    transform: rotateX(180deg);
    transform-origin: top;
  }
}*/


</style>